name: Create release on tag push

on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    name: Create mod release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          draft: true
